#%RAML 1.0
title: Order Service
version: v1
baseUri: /orders

types:
  Order:
    properties:
      id: string
      quantity: number
      totalPrice: number

    example:
      id: "123"
      quantity: 115
      totalPrice: 11500000

  OrderList:
    type: Order []


resourceTypes:
  GET:
    get:
      responses:
        200:
          body:
            application/json:
              type: <<item>>

/:
  /list:
    type:  { GET: {item : OrderList } }

  /{id}:
    type:  { GET: {item : Order } }
